# Generated by Django 5.0.4 on 2024-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_comment_user_comment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.AddField(
            model_name='reply',
            name='email',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
